Controllers/DataScienceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ZeroToHero.Controllers
{
    public class DataScienceController : Controller
    {
        // GET: DataScience
        public ActionResult ArtificialIntelligence()
        {
            return View();
        }

        public ActionResult MachineLearning()
        {
            return View();
        }

        public ActionResult Python()
        {
            return View();
        }


    }
}

Controllers/ElectricalEngineeringController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ZeroToHero.Controllers
{
    public class ElectricalEngineeringController : Controller
    {
        // GET: ElectricalEngineering
        public ActionResult ElectricalMachies()
        {
            return View();
        }

        public ActionResult Matlab()
        {
            return View();
        }

        public ActionResult PowerSystems()
        {
            return View();
        }
    }
}

Controllers/FullStackDeveloperController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ZeroToHero.Controllers
{
    public class FullStackDeveloperController : Controller
    {
        // GET: FullStackDeveloper
        public ActionResult HTML()
        {
            return View();
        }

        public ActionResult Css()
        {
            return View();
        }

        public ActionResult BootStrap()
        {
            return View();
        }

        public ActionResult TSql()
        {
            return View();
        }

        public ActionResult CSharp()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ZeroToHero.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

Controllers/IslamicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ZeroToHero.Controllers
{
    public class IslamicController : Controller
    {
        // GET: Islamic
        public ActionResult Quran()
        {
            return View();
        }

        public ActionResult Sunnah()
        {
            return View();
        }

        public ActionResult NewMuslim()
        {
            return View();
        }
    }
}

Controllers/LanguagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ZeroToHero.Controllers
{
    public class LanguagesController : Controller
    {
        // GET: Languages
        public ActionResult Arabic()
        {
            return View();
        }

        public ActionResult English()
        {
            return View();
        }

        public ActionResult Korean()
        {
            return View();
        }

        public ActionResult Turkish()
        {
            return View();
        }

    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "Know your instructor...";
}
<h2>@ViewBag.Title.</h2>

<p>Hey!!!!</p>
<p>This is Maher, I like sports, and chess.</p>
<p>I am attending an IT course @@ TMC, I am enjoying that</p>
<p>I would like to thank Br. Fakir for this oppurtunity 😊</p>

Views/Home/Contact.cshtml
@{    ViewBag.Title = "Instructor's Contact information";
}
<h2>@ViewBag.Title.</h2>
<address>
    2008 Temple Terrace DR.<br />
    Tampa, FL 33613<br />
    <abbr title="Phone">☎:</abbr>
    813.555.8122
</address>

<address>
    <strong>Email:</strong>   <a href="mailto:Mahertb2004@gmail.com">Mahertb2004@gmail.com</a><br />
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/content/video.css")
    @Styles.Render("~/content/general.css")

    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Zero To Hero", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Data Sciences
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>@Html.ActionLink("Python", "Python", "DataScience")</li>
                            <li>@Html.ActionLink("Machine Learning", "MachineLearning", "DataScience")</li>
                            <li>@Html.ActionLink("Artificial Intelligence", "ArtificialIntelligence", "DataScience")</li>
                        </ul>
                    </li>


                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            FullStack Developer
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>@Html.ActionLink("HTML", "HTML", "FullStackDeveloper")</li>
                            <li>@Html.ActionLink("Css", "Css", "FullStackDeveloper")</li>
                            <li>@Html.ActionLink("Boot Strap", "BootStrap", "FullStackDeveloper")</li>
                            <li>@Html.ActionLink("T-Sql", "TSql", "FullStackDeveloper")</li>
                            <li>@Html.ActionLink("C#", "CSharp", "FullStackDeveloper")</li>

                        </ul>
                    </li>


                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Electrical Engineering
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>@Html.ActionLink("Electrical Machies", "ElectricalMachies", "ElectricalEngineering")</li>
                            <li>@Html.ActionLink("Power Systems", "PowerSystems", "ElectricalEngineering")</li>
                            <li>@Html.ActionLink("Matlab", "Matlab", "ElectricalEngineering")</li>
                        </ul>
                    </li>


                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Languages
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>@Html.ActionLink("Arabic", "Arabic", "Languages")</li>
                            <li>@Html.ActionLink("English", "English", "Languages")</li>
                            <li>@Html.ActionLink("Turkish", "Turkish", "Languages")</li>
                            <li>@Html.ActionLink("Korean", "Korean", "Languages")</li>
                        </ul>
                    </li>


                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Islamic
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>@Html.ActionLink("New Muslims", "NewMuslim", "Islamic")</li>
                            <li>@Html.ActionLink("Quran", "Quran", "Islamic")</li>
                            <li>@Html.ActionLink("Sunnah", "Sunnah", "Islamic")</li>
                        </ul>
                    </li>

                    <!--<li>@Html.ActionLink("Home", "Index", "Home")</li> -->
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>



                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>